permalink: /:title
collections:
    games:
        output: true
        permalink: /games/:title
    hs-academia:
        output: false
    posts:
        output: true
        permalink: /blog/:title
